name:                hatris
version:             1.0.0.0
github:              "Natan-P/hatris"
license:             BSD-3-Clause
author:              "Natan"
maintainer:          "npolenec@gmail.com"
copyright:           "2024 Natan"

extra-source-files:
- README.md
- CHANGELOG.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/Natan-P/hatris#readme>

dependencies:
- base >= 4.7 && < 5
- brick
- vty
- text
- microlens-th
- microlens-mtl
- microlens
- containers
- mtl
- random-shuffle
- random
- time

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-export-lists
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src

executables:
  hatris:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hatris

tests:
  hatris-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - hatris
